services:
  # Создаем сервис с названием - backend
  backend:
    # Даем понятное имя контейнеру -  django_app
    container_name: django_app

    # Собираем образ из Dockerfile. Выше мы уже выполняли эту команду)
    build:
      context: .  # указываем путь где лежит этот Dockerfile. У меня в корне.
      dockerfile: Dockerfile  # Используем инструкции из файла Dockerfile
      # Иногда названия могут быть другие, например Dockerfile.prod - для продакшена

    # запускаем наш проект, как все собрали
    command: poetry run python src/manage.py runserver 0.0.0.0:8000

    # Синхронизируем папки: связываем текущую папку на компьютере с папкой /app в контейнере
    volumes:
      - .:/app

    # Указываем рабочую папку внутри контейнера (где лежит наш код)
    working_dir: /app

    # Открываем порт 8000: связываем порт твоего компьютера с портом контейнера
    ports:
      - "8000:8000"